export { default as Tabs } from "./Tabs"
export { default as TabTitle } from "./TabTitle"
export { default as TabContent } from "./TabContent"
export { default as Tab } from "./Tab"
export { TabsProps, TabTitleProps, TabContentProps } from "./Tabs.types"